name: Cross platform build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Install libcurl (per-OS)
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "macOS" ]]; then
          brew update
          brew install curl
          # Homebrew's curl is keg-only. Help CMake find headers/libs:
          echo "CMAKE_PREFIX_PATH=$(brew --prefix curl)" >> $GITHUB_ENV
        elif [[ "$RUNNER_OS" == "Linux" ]]; then
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev
        fi

    - name: Configure CMake
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          cmake -S . -B "$(cygpath -u "${{ steps.strings.outputs.build-output-dir }}")" -DCMAKE_BUILD_TYPE=DEBUG
          cmake --build "$(cygpath -u "${{ steps.strings.outputs.build-output-dir }}")" --config Release
        else
          cmake -S . -B ${{ steps.strings.outputs.build-output-dir }} -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -DCMAKE_BUILD_TYPE=DEBUG
          cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release
        fi

    - name: Run
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          exe_path="$(cygpath -u "${{ steps.strings.outputs.build-output-dir }}")/Release/main.exe"
          echo "Running: $exe_path"
          "$exe_path"
        else
          cd ${{ steps.strings.outputs.build-output-dir }}
          ./main
        fi
